AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "README.md"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Naming/PredicatePrefix:
  Exclude:
    - "lib/rspec/json_api/matchers.rb"

Naming/PredicateMethod:
  Exclude:
    - "lib/rspec/json_api/schema_match.rb"
